### PR TITLE
Make DDF application more robust

### PR DESCRIPTION
**Pull request by adrabent**
If the user wants only to use a subset of data to process with this pipeline (s)he has to select exactly the same data chunks as created by the DDF pipeline. With these changes one can use a random sample or selection of subbands.

### CODE REVIEW

**Comment by tikk3r** [comment]
Isn't the data chunk thing taken care of by the sort and concat steps already (as in, that will add missing subbands as dummies)? It's also not safe to immediately concatenate them, because each h5parm can have (and typically has) a different spacing in time and frequency. For subsequent subtraction of the LoTSS map you will need the data blocks to match exactly to DDF as well.

**Comment by adrabent** [comment]
> Isn't the data chunk thing taken care of by the sort and concat steps already (as in, that will add missing subbands as dummies)?

Should be. I got results from DDF by the Surveys pipeline and it didn't match. I hardly could understand why, since the spacings looked all fine.

> It's also not safe to immediately concatenate them, because each h5parm can have (and typically has) a different spacing in time and frequency

It is not? All of mine have exactly the same spacing in time and frequency. So it worked pretty smoothly and was the only way in order to avoid re-running everything again.

> For subsequent subtraction of the LoTSS map you will need the data blocks to match exactly to DDF as well.

When is this step performed in the pipeline?

**Comment by tikk3r** [comment]
> Should be. I got results from DDF by the Surveys pipeline and it didn't match. I hardly could understand why, since the spacings looked all fine.

Interesting. What's fed to DDF is the prefactor sorted output, and as far as I know the code here is the same.


> It is not? All of mine have exactly the same spacing in time and frequency. So it worked pretty smoothly and was the only way in order to avoid re-running everything again.

Not necessarily. For example, on my field some blocks have 1198 timeslots + 5 frequency slots, others 899 timeslots and 10 frequency slots and others again 599 timeslots and 10 frequency slots. It would possible to interpolate them to a common grid and then concatenate of course.

> When is this step performed in the pipeline?

Not in this pipeline. It becomes relevant for widefield imaging and it requires DDFacet.

**Comment by adrabent** [comment]
> What's fed to DDF is the prefactor sorted output, and as far as I know the code here is the same.

That's true. But if I don't provide the full bandwidth (because I can only analyse chunks of it), the chunks will deviate, unless I reallly carefull check that the subbands really match.
And even this might not work like in my case, since the solution chunks provided by DDF differ from those created by the regular target pipeline:

chunk1:
L643429_SB347_uv.pre-cal_12B9CACE8t_142MHz.pre-cal.ms | 141,899 | L643429_SB347_uv_12B9CACE5t_142MHz.msdpppconcat | 141,899

chunk2:
L643429_SB356_uv.pre-cal_12B9CACE8t_144MHz.pre-cal.ms | 143,657 | L643429_SB347_uv_12B9CACE5t_144MHz.msdpppconcat | 143,852

chunk3:
L643429_SB366_uv.pre-cal_12B9CACE8t_146MHz.pre-cal.ms | 145,61 | L643429_SB347_uv_12B9CACE5t_146MHz.msdpppconcat | 145,805

chunk4:
L643429_SB375_uv.pre-cal_12B9CACE8t_148MHz.pre-cal.ms | 147,563 | L643429_SB347_uv_12B9CACE5t_148MHz.msdpppconcat | 147,758

I don't why it deviates by 0.195kHz from the first to the second chunk (the rest have the proper spacing of 1,95 MHz). Maybe this is a bug, but LB-pipeline chunks have the right spacing, the DDF chunks don't.

> It would possible to interpolate them to a common grid and then concatenate of course.

Ah right.. I also found now some frequency ranges where it differs. Concatenating the h5parm is still possible. H5parm does not require a equidistant spacing in time or frequency. DPPP uses nearest neighbour interpolation when applying these solutions and thus should work with it as well.

> For subsequent subtraction of the LoTSS map you will need the data blocks to match exactly to DDF as well.

Isn't this a rather limiting constraint? Anyway, I think this still does not touch the way how one could combine solutions to apply it to the data in a more robust way. To me, for the subtraction it seems to be rather related on what data you may want to use if you want to proceed with other 3rd party pipelines.

**Comment by tikk3r** [comment]
> I don't why it deviates by 0.195kHz from the first to the second chunk (the rest have the proper spacing of 1,95 MHz). Maybe this is a bug, but LB-pipeline chunks have the right spacing, the DDF chunks don't.

Ah good point about reducing a variable amount of data. I'm also not sure why those spacings would be different.

> Ah right.. I also found now some frequency ranges where it differs. Concatenating the h5parm is still possible. H5parm does not require a equidistant spacing in time or frequency. DPPP uses nearest neighbour interpolation when applying these solutions and thus should work with it as well.

I see, I thought solutions had to be equidistant. I don't know why, but I had problems concatenating them, because of the spacing. If that works, then it's fine.

> Isn't this a rather limiting constraint?

Probably it's not as tight as I made it sound. You need the DD solutions from the ddf-pipeline for the subtract, so the more accurate you can mimic the data they were derived from, the better I'd think. As long as the relevant frequency and time ranges are covered in the data it's probably good. 

Keeping these blocks matched was to match LoTSS and because of the problems I had with concatenating the h5parms. If this is more robust then all the more reason to implement it :) (would still need a test of course to see how much it differs from perfectly matched blocks)

You're right that subtraction is a bit specific. For a single target it probably doesn't matter that much, but it is necessary for widefield imaging of a field.

**Review by lmorabit — APPROVED** [review]
approving this at the moment but we should introduce a script at the beginning to NOT process the subbands we won't use in the first place.

**Pull request merged**
